# -*- coding: utf-8 -*-
"""파이썬코드.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H_nn0BrprCGJvxOtfKTDZVp84cWsTxQU
"""

print("--- 커리어 탐색 및 추천 서비스 ---")

# (1) 산경공 전체 전공
all_majors = [
    "창의적공학설계", "기술경영개론", "객체지향프로그래밍", "경제성공학", "공급사슬관리", "데이터베이스",
    "기초경영과학", "생산운영관리", "실험계획법", "인간공학", "경영정보시스템", "경영과학응용",
    "설비관리", "의사결정론", "빅데이터분석", "캡스톤디자인", "제품개발론"
]

# (2) 산업경영공학의 적합한 성향 목록
all_traits = [
    "분석적 성향", "논리적 사고", "시스템적 사고", "문제 해결 능력", "데이터 기반 의사결정",
    "창의적 사고", "대인 커뮤니케이션 및 협업", "실행력", "메이킹"
]

# (3) 직업 정보
careers = {
    "경영 컨설턴트": {
        "m": ["경영과학응용", "의사결정론", "기술경영개론"], # m= 전공
        "t": ["논리적 사고", "분석적 성향", "시스템적 사고"], # t= 성향
        "c": ["ADsP", "경영지도사"], # c= 필요자격증
        "r": "논리적 사고와 분석적 성향이 뛰어나고, 의사결정 및 기술경영 과목에 높은 선호도를 보였습니다." # r= 추천이유
    },
    "물류 관리 전문가": {
        "m": ["공급사슬관리", "기초경영과학", "생산운영관리"],
        "t": ["시스템적 사고", "분석적 성향", "실행력"],
        "c": ["물류관리사", "CPIM(국제자격증)"],
        "r": "시스템적 사고력이 강하고 공급사슬관리 및 생산운영 관련 과목에 대한 선호도와 성취도가 높습니다."
    },
    "변리사": {
        "m": ["기술경영개론", "제품개발론", "경제성공학"],
        "t": ["논리적 사고", "창의적 사고", "분석적 성향"],
        "c": ["변리사 시험 (필수)", "기술거래사"],
        "r": "기술과 법률을 아우르는 지식과 논리적/창의적 사고가 돋보이며, 지식재산권 분야에 적합합니다."
    },
    "산업공학기술자": {
        "m": ["생산운영관리", "인간공학", "설비관리"],
        "t": ["문제 해결 능력", "실행력", "메이킹"],
        "c": ["산업안전기사", "공장관리기술사"],
        "r": "생산 공정 개선 및 설비 관리에 대한 선호도가 높으며, 실제 시스템을 만드는 실행력과 문제 해결 능력이 우수합니다."
    },
    "산업관리원": {
        "m": ["생산운영관리", "설비관리", "인간공학"],
        "t": ["시스템적 사고", "실행력", "대인 커뮤니케이션 및 협업"],
        "c": ["ERP 정보관리사(생산)"],
        "r": "생산 현장 관리와 원활한 커뮤니케이션 능력이 우수하여 현장과 관리의 가교 역할에 적합합니다."
    },
    "생산관리사무원": {
        "m": ["생산운영관리", "기초경영과학", "공급사슬관리"],
        "t": ["분석적 성향", "논리적 사고", "문제 해결 능력"],
        "c": ["ERP 정보관리사(생산)", "CPIM"],
        "r": "생산 계획 수립과 효율적인 운영을 위한 분석적 역량과 문제 해결 능력이 뛰어납니다."
    },
    "연구실 안전전문가": {
        "m": ["인간공학", "실험계획법"],
        "t": ["문제 해결 능력", "시스템적 사고", "분석적 성향"],
        "c": ["산업안전기사"],
        "r": "인간공학적 지식을 바탕으로 안전한 연구 환경을 조성하는 시스템적 사고와 문제 해결력이 있습니다."
    },
    "온실가스 인증심사원": {
        "m": ["경제성공학", "생산운영관리"],
        "t": ["분석적 성향", "데이터 기반 의사결정"],
        "c": ["온실가스 관리 산업기사"],
        "r": "환경 규제와 데이터 분석에 강하며, 경제성과 운영 효율을 고려한 지속 가능한 시스템 구축에 적합합니다."
    },
    "자재관리사무원": {
        "m": ["공급사슬관리", "생산운영관리", "데이터베이스"],
        "t": ["시스템적 사고", "실행력", "논리적 사고"],
        "c": ["물류관리사", "ERP 정보관리사(물류)"],
        "r": "자재의 흐름을 파악하는 시스템적 사고와 이를 효율적으로 관리하는 데이터 활용 능력이 좋습니다."
    },
    "정보시스템운영자": {
        "m": ["경영정보시스템", "데이터베이스", "객체지향프로그래밍"],
        "t": ["논리적 사고", "데이터 기반 의사결정", "분석적 성향"],
        "c": ["정보처리기사", "SQLD"],
        "r": "IT 시스템, 데이터베이스, 프로그래밍에 관심이 많고, 논리적 분석을 통해 시스템을 안정적으로 운영하는 능력이 있습니다."
    },
    "컴퓨터시스템분석가": {
        "m": ["경영정보시스템", "빅데이터분석", "의사결정론"],
        "t": ["분석적 성향", "논리적 사고", "시스템적 사고"],
        "c": ["정보처리기사", "PMP"],
        "r": "정보 시스템의 효율성을 높이는 고도화된 분석력과 시스템 설계 및 최적화 능력을 갖추고 있습니다."
    },
    "품질관리사무원": {
        "m": ["실험계획법", "생산운영관리"],
        "t": ["분석적 성향", "논리적 사고", "데이터 기반 의사결정"],
        "c": ["품질경영기사", "6시그마 자격"],
        "r": "실험계획법을 비롯한 통계/분석 과목에 우수하며, 객관적인 데이터 기반으로 품질을 관리하는 능력이 탁월합니다."
    },
    "품질인증심사전문가": {
        "m": ["실험계획법", "생산운영관리", "의사결정론"],
        "t": ["분석적 성향", "논리적 사고", "시스템적 사고"],
        "c": ["품질경영기사", "ISO 9001 심사원 자격"],
        "r": "표준과 원칙을 준수하며 논리적이고 시스템적인 사고를 통해 품질 경영 시스템을 심사하는 역량이 있습니다."
    }
}

print("\n--- 우선도를 정해주세요 ---")

# (1) 중요도(가중치) 입력
WEIGHT_MAJOR = 0
WEIGHT_TRAIT = 0
WEIGHT_A_GRADE = 0

print("\n[A] 각 항목의 중요도를 1~5점 사이의 숫자로 입력해 주세요.")

while True: #중요도 선택 반복문 작성 코드
    try: # 숫자가 아닌 문자를 넣었을때 튕김 방지용 코드
        WEIGHT_MAJOR = int(input("전공 선호도 중요도: "))
        WEIGHT_TRAIT = int(input("성향 일치도 중요도: "))
        WEIGHT_A_GRADE = int(input("A0 이상 과목 중요도: "))

        if not (1 <= WEIGHT_MAJOR <= 5 and 1 <= WEIGHT_TRAIT <= 5 and 1 <= WEIGHT_A_GRADE <= 5):
            print("\n 오류: 중요도는 반드시 1에서 5 사이의 정수여야 합니다. 다시 입력해 주세요.")
            continue #1~5사이의 숫자가 아닌 다른 숫자를 입력했을때 다시 하라고 경고 코드

        break

    except: # try - except 는 세트(친구) 문자 넣었을 때 다시 하라고 경고 코드
        print("\n 오류: 숫자를 입력해야 합니다. 다시 입력해 주세요.")
        continue

print(f"\n→ 최종 중요도: 전공 {WEIGHT_MAJOR}, 성향 {WEIGHT_TRAIT}, A0 {WEIGHT_A_GRADE}")


# (2) 전공 선호도 입력
print("\n[B] 전공 과목별 선호도를 1~5점 사이의 숫자로 입력하세요.")
major_scores = {}

for m in all_majors:
    while True:
        try:
            score = int(input(f"'{m}' 선호도 (1~5): ")) #선호도1~5입력코드
            if 1 <= score <= 5:
                major_scores[m] = score
                break
            else:
                print("1에서 5 사이의 숫자를 입력해야 합니다.")
        except:
            print("숫자를 입력해야 합니다.")


# (3) 성향 입력
print("[C] 성향 입력 (보기:", all_traits, ")")

input_text = input("입력(띄어쓰기 금지, 쉼표로 구분): ") #정확히 기입하기 경고문

traits = input_text.split(",") # split은 컴퓨터가 키워드를 하나하나 구분하기 위해 사용된 코드

print("결과:", traits)


# (4) A0 이상 과목 입력
a_grade = []
print("\n[D] A0 이상 받은 전공 과목을 쉼표로 구분하여 입력하세요.")

input_text = input("입력 (없으면 엔터): ")

if input_text == "":
    a_grade = [] # 아무것도 안 적었으면 빈 리스트
else:
    # 띄어쓰기 없이 '과목A,과목B' 형태로 정확히 입력해야 함.
    a_grade = input_text.split(",") # split은 컴퓨터가 키워드를 하나하나 구분하기 위해 사용된 코드

print(f"입력 결과: {a_grade}")



# 점수 계산 및 결과 출력
print("\n--- 점수 계산이 완료되었습니다. ---")

results = {}
# 반복문을 돌며 모든 직업을 하나씩 검사하게(너가 입력한 정보와 모든 전공과의 연관성) 만드는 코드
for job_name, job_info in careers.items():  #.items()은 딕셔너리의 '직업명'와 '점수'을 한 번에 꺼내오는 함수
    print(f"\n[계산] {job_name} 직업에 대한 점수를 계산합니다.")
    current_score = 0

    # A) 전공 선호도 점수 계산
    major_score_sum = 0
    required_majors = job_info["m"]
    # 사용자가 점수를 매긴 전공인지 확인 (데이터 존재 여부 체크)
    for required_m in required_majors:
        if required_m in major_scores:
            score = major_scores[required_m]
            major_score_sum = major_score_sum + score
            print(f"   - 전공 '{required_m}': 선호도 {score}점 추가.")
    # 단순 합계에 '가중치(중요도)'를 곱해서 점수 비중을 조절
    score_part1 = major_score_sum * WEIGHT_MAJOR
    current_score = current_score + score_part1
    print(f"   -> 전공 점수 총합 ({major_score_sum}) * 중요도 ({WEIGHT_MAJOR}) = {score_part1}점")

    # B) 성향 일치 점수 계산
    trait_match_count = 0
    required_traits = job_info["t"]
    for required_t in required_traits:
        if required_t in traits:
            trait_match_count = trait_match_count + 1
            print(f"   - 성향 '{required_t}': 일치 (+1점).")

    score_part2 = trait_match_count * WEIGHT_TRAIT
    current_score = current_score + score_part2
    print(f"   -> 성향 일치 개수 ({trait_match_count}) * 중요도 ({WEIGHT_TRAIT}) = {score_part2}점")

    # C) A0 과목 일치 점수 계산
    a_match_count = 0
    for a_item in a_grade:
        if a_item in required_majors:
            a_match_count = a_match_count + 1
            print(f"   - A0 과목 '{a_item}': 일치 (+1점).")

    score_part3 = a_match_count * WEIGHT_A_GRADE
    current_score = current_score + score_part3
    print(f"   -> A0 일치 개수 ({a_match_count}) * 중요도 ({WEIGHT_A_GRADE}) = {score_part3}점")

    results[job_name] = current_score
    print(f"   => 최종 점수: {current_score}점")


print("\n" + "="*50)
print("           --- 4. 최종 추천 결과 ---")
print("="*50)

# (1) 가장 높은 점수를 찾기 및 (2) 결과 정렬
best_job = ""
max_score = -1
sorted_list = []
# 나중에 점수순으로 정렬하기 위해 (점수, 직업명) 튜플 형태로 리스트에 추가
for job_name, score in results.items():
    sorted_list.append((score, job_name))
    # 최댓값 찾기 (현재 점수가 지금까지의 최대 점수보다 크면 갱신하게)
    if score > max_score:
        max_score = score
        best_job = job_name
# .sort()은 리스트를 정렬하는 함수
# reverse=True(역순)라는 옵션을 주어 점수가 높은 순(내림차순)으로 정렬함
sorted_list.sort(reverse=True)

# (3) 최종 추천 직업 정보 출력
if best_job:
    best_info = careers[best_job]
    print(f"\n 최종 추천 직업: **{best_job}** (최고 점수: {max_score})")
    print("-" * 35)
    print(f" **적합 이유**: {best_info['r']}")
    print("-" * 35)
    print(" 관련 핵심 전공:", ", ".join(best_info["m"]))
    print(" 필요 성향:", ", ".join(best_info["t"]))
    print(" 추천 자격증:", ", ".join(best_info["c"]))
else:
    print("\n추천 결과를 계산할 수 없습니다. 직업 정보를 확인해 주세요.")

# (4) 전체 순위 출력
print("\n전체 직업 순위 (점수 높은 순)")
# enumerate()는 리스트의 '순서'와 '값'을 동시에 반환하는 함수 (순위 매길 때 필요해용)
for rank, (score, job_name) in enumerate(sorted_list):
    print(f"  {rank + 1}위. {job_name}: {score}점")

